### ISSUE TITLE
New advancements tracker

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1002]
This issue contains a list of things not well enough defined / important enough yet for its own ticket, but worth exploring when there's more capacity.

```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/noports/issues/1005
- [ ] https://github.com/atsign-foundation/noports/issues/1003
- [ ] NP cli wrapper / TUI
- [ ] A proper VPN client
```

**Comment by xavierchanth** [comment]
Closing, we have separate tickets for the things we have plans on pursuing.
