### ISSUE TITLE
[Tracker] NPT Desktop App

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1003]
- Desktop application for No Ports Tunnel
- Possibly less UI dependent, and provide a system tray for quick access
  - Since the main use case is for it to be in the background while using other applications.
```[tasklist]
### Tasks (Nov 2024)
- [x] -- SETTINGS ICON --
- [ ] https://github.com/atsign-foundation/noports/issues/1486
- [ ] https://github.com/atsign-foundation/noports/issues/1487
- [ ] -- TRANSLATIONS & TEXT --
- [ ] https://github.com/atsign-foundation/noports/issues/1488
- [ ] https://github.com/atsign-foundation/noports/issues/1491
- [ ] -- STATUS & BUTTONS --
- [ ] https://github.com/atsign-foundation/noports/issues/1496
- [ ] Retry button if connection fails. Do we want to do this? Or keep the play button?
- [ ] “Oh I also had on/off instead of play/stop (maybe we can do that for clarity, especially for when it’s the first time someone looks at a profile)”
- [ ] https://github.com/atsign-foundation/noports/issues/1501
- [ ] https://github.com/atsign-foundation/noports/issues/1502
- [ ] https://github.com/atsign-foundation/noports/issues/1503
- [ ] -- #1520
- [ ] Get Started > Next (without entering an atSign) > Get a free atSign.. It takes you back to the start screen instead of an atSign generator
- [ ] Get Started > Next (without entering an atSign) > Upload atKeys > Cancel .. The app disappears into the background
- [ ] Get Started > Next (without entering an atSign) > Upload atKeys > Upload corrupt or invalid keys > “Notice .. Auth Failed” on screen
- [ ] Get Started > Next (without entering an atSign) > Activate atSign > Activate (without entering an atSign).. The app goes back to the previous screen instead of showing text saying the person should enter their atSign
- [ ] Get Started > Next (without entering an atSign) > Activate atSign > Enter a non-existent atSign and click Activate > “Notice.. Unauthorized” on screen
- [ ] Get Started > Enter an unactivated atSign and click Next > Activate atSigns > Enter atSign again and click Activate > It hangs on the “Fetching atSign Status” screen
- [ ] Get Started > Next (without entering an atSign).. It proceeds to the next screen. What’s the point of entering an atSign then? Similarly if you enter an atSign you want to activate, it still asks you to enter the atSign you want to activate two screens later.
- [ ] -- NICHE BUGS & FEATURES --
- [ ] List sorting for profiles
- [ ] https://github.com/atsign-foundation/noports/issues/1268
- [x] It’s not clear that you need to scroll sideways to see more RV options. Maybe we lock the width to a minimum that doesn’t require side scrolling?
- [ ] When you onboard, switch assigns and then try to onboard again it doesn’t show the atsign  saved on the drop down but it works when typed in
- [ ] https://github.com/atsign-foundation/noports/issues/1269
- [ ] After first connection.. we should add a “what next” popup that tells the person they can now do whatever they want
- [ ] https://github.com/atsign-foundation/noports/issues/1515
- [ ] https://github.com/atsign-foundation/noports/issues/1519
- [ ] https://github.com/atsign-foundation/noports/issues/1493
- [ ] https://github.com/atsign-foundation/noports/issues/1518
- [ ] https://github.com/atsign-foundation/noports/issues/1517
- [ ] https://github.com/atsign-foundation/noports/issues/1516
- [ ] https://github.com/atsign-foundation/noports/issues/1566
```

```[tasklist]
### Tasks (Original)
- [ ] https://github.com/atsign-foundation/noports/issues/1204
- [ ] https://github.com/atsign-foundation/noports/pull/1275
- [ ] https://github.com/atsign-foundation/noports/issues/1267
- [ ] https://github.com/atsign-foundation/noports/issues/1271
- [ ] https://github.com/atsign-foundation/noports/issues/1270
- [ ] https://github.com/atsign-foundation/noports/issues/1272
- [ ] https://github.com/atsign-foundation/noports/issues/1273
- [ ] https://github.com/atsign-foundation/noports/issues/1274
- [ ] https://github.com/atsign-foundation/noports/issues/1303
- [ ] https://github.com/atsign-foundation/noports/issues/1359
- [ ] https://github.com/atsign-foundation/noports/issues/1360
- [ ] https://github.com/atsign-foundation/noports/issues/1361
- [ ] https://github.com/atsign-foundation/noports/issues/1371
- [ ] https://github.com/atsign-foundation/noports/issues/1382
- [ ] https://github.com/atsign-foundation/noports/issues/1412
- [ ] https://github.com/atsign-foundation/noports/issues/1445
```

**Comment by xavierchanth** [comment]
We don't really need a dedicated tracker anymore
