### ISSUE TITLE
[Tracker] C at_activate

### ISSUE THREAD

**Issue by JeremyTubongbanua** [atsign-foundation/noports#1324]
This is a tracker ticket for the C version of `at_activate`

## Dependencies

These need to be completed before we even start writing the `at_activate` program

`packages/atchops`
- [x] RSA Key Generation https://github.com/atsign-foundation/at_c/issues/74

`packages/atcommons`
- [x] Enrol Verb Builder https://github.com/atsign-foundation/at_c/issues/165
- [x] CRAM Verb Builder https://github.com/atsign-foundation/at_c/issues/165

`packages/atauth`
- [ ] Registrar API Interface https://github.com/atsign-foundation/at_c/issues/397
- [ ] Enrollment Interface https://github.com/atsign-foundation/at_c/issues/399
- [x] CRAM Onboarding https://github.com/atsign-foundation/at_c/issues/176
- [x] APKAM Subsequent Authentication Support https://github.com/atsign-foundation/at_c/issues/287
- [ ] Move PKAM Authentication to atauth  https://github.com/atsign-foundation/at_c/issues/398

## Main Application

The ticket for actually writing at_activate

- [ ] https://github.com/atsign-foundation/at_c/issues/293

**Comment by srieteja** [comment]
Implementing multiple task list items in the same branch/PR; will check the code at once to save time. Completed implementation to support CRAM auth through at_c client. Carrying to PR97 to implement key/keypair generation and exchange these keys with the at_server.

**Comment by gkc** [comment]
@XavierChanth @JeremyTubongbanua can we close this ticket?

**Comment by xavierchanth** [comment]
There’s some more refinements to be made before we can close this ticket
