### ISSUE TITLE
[Tracker] SSH No Ports

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#135]
Leads: @cconstab @XavierChanth 

```[tasklist]
### TODO
- [ ] https://github.com/atsign-foundation/sshnoports/issues/163
- [ ] https://github.com/atsign-foundation/operations/issues/45
- [ ] https://github.com/atsign-foundation/operations/issues/73
- [ ] https://github.com/atsign-foundation/sshnoports/issues/218
- [ ] https://github.com/atsign-foundation/sshnoports/issues/219
- [ ] https://github.com/atsign-foundation/sshnoports/issues/234
- [ ] https://github.com/atsign-foundation/sshnoports/issues/235
- [ ] https://github.com/atsign-foundation/sshnoports/issues/104
- [ ] https://github.com/atsign-foundation/sshnoports/issues/184
- [ ] https://github.com/atsign-foundation/sshnoports/issues/277
- [ ] https://github.com/atsign-foundation/sshnoports/issues/287
- [ ] https://github.com/atsign-foundation/docs/issues/5
- [ ] https://github.com/atsign-foundation/sshnoports/issues/269
- [ ] https://github.com/atsign-foundation/sshnoports/issues/305
- [ ] https://github.com/atsign-foundation/sshnoports/issues/304
- [ ] https://github.com/atsign-foundation/sshnoports/issues/270
- [ ] https://github.com/atsign-foundation/sshnoports/issues/299
- [ ] https://github.com/atsign-foundation/sshnoports/issues/295
- [ ] https://github.com/atsign-foundation/sshnoports/issues/294
- [ ] https://github.com/atsign-foundation/sshnoports/issues/220
- [ ] https://github.com/atsign-foundation/sshnoports/issues/293
```

**Comment by cconstab** [comment]
demo gif 

![sshnp3](https://github.com/atsign-foundation/sshnoports/assets/6131216/232a2443-d93f-43b2-95bc-e09b82d5c4db)

**Comment by cconstab** [comment]
demo 2
![sshnp2](https://github.com/atsign-foundation/sshnoports/assets/6131216/4ff005f1-230e-4621-9b33-f834caa9a1d1)

**Comment by xavierchanth** [comment]
I'm closing this, I've been trying to keep this issue up to date, but this project is much bigger than a single tracker card.
