### ISSUE TITLE
Release NoPorts desktop

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#1450]
```[tasklist]
### Tasks
- [x] Complete and merge #1412
- [x] Translate and add any missing localization strings #1303
- [ ] Create app store description & screen shots
- [x] Prepare the app store release
```
