### ISSUE TITLE
sshnp - list devices

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#184]
### Is your feature request related to a problem? Please describe.

Can't really tell what devices can be connected to, especially in an organization where you may have had an admin setup sshnpd for you.

### Describe the solution you'd like

A subcommand / flag which allows you to list available devices for connecting to.

### Additional context

Depending on the implementation, the client may have to state that only devices with version greater than x.x.x will be listed...
```[tasklist]
### Tasks
- [x] sshnpd - internal schedule with ttl to create/refresh device key (json structure with devicename, metadata of installed version, and room for info)
- [x] sshnpd - monitor for ping notifications and respond with a device name notification
- [x] sshnp - grab key list for all clients
- [x] sshnp - ping notification and wait up to 5 seconds for response
- [ ] https://github.com/atsign-foundation/sshnoports/issues/371
```

**Comment by xavierchanth** [comment]
A notification from clients which daemons respond to, or put an atKey shared with the client/manager atsign

**Comment by cconstab** [comment]
I like the notification route best.. This way only listening sshnpd's respond.. using an atKey could leave some "junk" in place.

**Comment by gkc** [comment]
I'd like to see a list of all of my devices, with the ones which respond marked as such

Junk is a valid concern but could be mitigated with a suitable ttl e.g. N days?

i.e. a combination of
- sshnpd makes a key for the device saying what version it is running and when it was last started
- sshnp retrieves that list
- sshnp also sends a 'ping' notification which all sshnpds listen for
- running sshnpds respond to ping notifications

**Comment by xavierchanth** [comment]
I've started the work on this based on what @gkc listed above. Will resume in this sprint after addressing some of the other issues first.

**Comment by xavierchanth** [comment]
The initial implementation is available in #285 
Enough to allow me to progress with #234

**Comment by xavierchanth** [comment]
Last step is less related to this issue so I've made it a separate issue so that this can be closed
