### ISSUE TITLE
feat: Do direct ssh when using an rv

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#218]
Sshnp no double ssh option - as we have the rv we do not have to double ssh. Option shpuld still be there and only used if needed. I.E. a direct connectoon (-h with no @)

```[tasklist]
### Tasks
- [x] **Design** Spike implementation to prove it
- [x] **daemon** Refactor to cleanly separate new request notification handling from previous versions and allow the relevant code to be fully reused
- [x] **daemon** Implement stub handler for new request notification
- [x] **daemon** Implement full handler for new request notification format where double ssh is requested, to prove backwards compatibility
- [x] **daemon** Implement full handler for new request notification format where direct ssh is requested
- [x] **client** Refactor to clearly separate new request notification sending from previous versions while allowing reusability
- [x] **client** Add a version check to determine whether to use new or legacy request notification format30m
- [x] **client** Implement new request sender
- [ ] **Test** Augment end-to-end tests to cover both direct ssh and double ssh
```

**Comment by gkc** [comment]
Spiked at the weekend and got this working albeit resulted in a bunch of bug-prone hard-to-grok difficult-to-maintain code. See plan in issue description above

**Comment by gkc** [comment]
This is complete except for the last task (Augment end-to-end tests to cover both direct ssh and double ssh) which is also covered in the release 4.0.0 tracker, so will close this ticket as completed.
