### ISSUE TITLE
SSHNPD (Python Implementation)

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#220]
A Python implementation of sshnpd open to extension/modification for self-hosting

```[tasklist]
### Tasks
- [x] implement notifications from at_python
- [x] create reverse ssh tunnel using the paramiko module
- [x] send a notification back to sshnp
- [x] replace paramiko with sys calls
- [x] resolving remaining connections before ending program
```

**Comment by cconstab** [comment]
@cpswan something you would like to take on ?

**Comment by Xlin123** [comment]
I'm interested!

**Comment by cpswan** [comment]
@realvarx has notifications working now with at_python, which is one of the foundational things needed for this.

**Comment by Xlin123** [comment]
I should've put this here earlier but here's the branch #259

**Comment by cpswan** [comment]
Closed on project board, but not here.
