### ISSUE TITLE
[Tracker] SSHNP - Docker Feedback

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#270]
```[tasklist]
### Tasks
- [x] Don't loop in docker image entrypoint, docker should be responsible for choosing to restart
- [x] at_activate - provide a docker image for use with activating the sshnpd docker image
- [x] Allow rebuilds with dockerhub build script by removing the "+<number>" from the tag
- [x] Remove latest from default build
- [x] Separate promote latest script
```

**Comment by xavierchanth** [comment]
Odds and ends that I need cleanup / do in docker for customers, not super urgent as we've addressed all of the immediate problems.

**Comment by gkc** [comment]
Setting to P2

**Comment by xavierchanth** [comment]
Checking: 'Allow rebuilds with dockerhub build script by removing the "+<number>" from the tag'

As we should never have to create a tag with a +build_number, we should only ever rebuild by doing a run of the dockerhub sshnpd script on the same tag. If we are on a different commit, then it should at least be a patch increase.
