### ISSUE TITLE
[Tracker]: No Ports Desktop V1.0.0

### ISSUE THREAD

**Issue by CurtlyCritchlow** [atsign-foundation/noports#717]
Due to the active nature of No Ports, and to prevent scope creep below are the list of tasks that needs to be completed for us to consider No Ports Desktop V1 ready to be published. Please add your task below so we can have a consensous on the remaining work to publish No Ports Desktop.

```[tasklist]
### No Ports Desktop V1 tasks to be completed
- [x] Complete #716
- [x] Complete  #712
- [x] Complete #713
- [x] Complete #722
- [x] Complete #723
- [x] Complete #733
- [x] Complete #754
- [x] Fix https://github.com/atsign-foundation/noports/issues/731
- [x] Complete #758
- [x] Complete #709
- [x] Complete https://github.com/atsign-foundation/noports/issues/776
- [x] Complete https://github.com/atsign-foundation/noports/issues/775
- [x] Complete #819
- [x] Complete #820
- [x] Complete #786
- [x] Complete #790
- [x] Complete #821
```

**Comment by gkc** [comment]
Added #722 and #723 to the list

**Comment by xavierchanth** [comment]
Buggy nav bar

https://github.com/atsign-foundation/noports/assets/33691921/01b489c7-a754-44d9-b44b-b75163256dd8

**Comment by CurtlyCritchlow** [comment]
Current build on microsoft and apple store is v1.0.0+5
