### ISSUE TITLE
Make universal.sh more robust

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/noports#911]
### Is your feature request related to a problem? Please describe.

Once we have the universal installer working we should add additional checks to ensure that it doesn't fail for predictable reasons.

### Describe the solution you'd like

```[tasklist]
### Tasks
- [x] Check for the existence of required tools (e.g. `tar` before running them) [curl, wget, crontab, tmux, sudo]
- [x] Wrap curl / wget to use whatever is available on the system
- [x] silent mode
- [x] Suggest running script as root (using sudo) for a systemd install
- [x] Create authorized keys file if it doesn't exist
```

**Comment by xavierchanth** [comment]
I think this is good enough for now, it can be P3

**Comment by cpswan** [comment]
Dropping to 3SP for silent mode if this can be tackled in PR88

**Comment by xavierchanth** [comment]
@Xlin123 can you tackle silent mode in PR89?

**Comment by Xlin123** [comment]
Closed with #1146
