### ISSUE TITLE
v5.1.0 docs changes

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#934]
```[tasklist]
### Tasks
- [ ] migrate sshnp use-cases to npt where appropriate
- [ ] restructure site to "single" product hierarchy
- [ ] More documentation around the universal.sh installer
```
