### ISSUE TITLE
Improve release workflows & automation

### ISSUE THREAD

**Issue by xavierchanth** [atsign-foundation/noports#948]
```[tasklist]
### Tasks
- [x] Try to make it so that multibuild.yaml automatically uploads to the releases tab
- [ ] multibuild.yaml outputs a hash for releases which we can include in a table as part of the release notes
- [ ] Releases/builds created from tags should automatically update the version in pubspec.yaml & version.dart to match the git tag & then build [multibuild & docker images]
```
